version: '2'
services:
  wildfly:
    container_name: api-demo-wildfly
    build: api-demo-wildfly/
    image: "adesso/api-demo-wildfly"
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      - AUTH_SERVER_HOST=${EXTERNAL_IP}
      - AUTH_SERVER_PORT=8081
    links:
#      - keycloak:api-demo-keycloak

  keycloak:
    container_name: api-demo-keycloak
    build: api-demo-keycloak/
    image: "adesso/api-demo-keycloak"
    ports:
      - "8081:8080"
      - "9991:9990"
    environment:
      - KEYCLOAK_LOGLEVEL=DEBUG
